#!/usr/bin/env python

import rospy
from zzz_common.params import parse_private_args
from zzz_cognition_msgs.msg import MapState

from zzz_planning_msgs.msg import DecisionTrajectory
from nav_msgs.msg import Path 
from visualization_msgs.msg import Marker, MarkerArray

from zzz_planning_decision_continuous_models import MainDecision
from zzz_planning_decision_continuous_models.Werling.Werling_planner import Werling
from zzz_planning_decision_continuous_models.follow import Follow_Ref_Path




class DecisionNode(object):
    def __init__(self):

        params = parse_private_args(
            decision_trajectory_topic="decision_trajectory",
            dynamic_map_topic="/zzz/cognition/local_dynamic_map/map_with_ref",
            RVIZ_decision_trajectory_topic="decision_trajectory_path", 
            RVIZ_all_trajectory_topic="all_trajectory_path", 
            RVIZ_predi_trajectory_topic="predi_trajectory_path", 
            RVIZ_collision_circle_topic="collision_circle", 
            RVIZ_received_ref_path_topic="temp_planning_received_ref_path",
            hz = 5,
        )
        self._rate = rospy.Rate(params.hz)

        model_trajectory = Werling()
        self._decision_instance = MainDecision(trajectory_planner=model_trajectory)

        # ROS messages
        self._dynamic_map_subscriber = rospy.Subscriber(params.dynamic_map_topic, MapState, self._decision_instance.receive_dynamic_map)
        self._decision_trajectory_publisher = rospy.Publisher(params.decision_trajectory_topic, DecisionTrajectory, queue_size=1)
        
        self._rviz_decision_trajectory_publisher = rospy.Publisher(params.RVIZ_decision_trajectory_topic, Path, queue_size=1)
        self._rviz_all_trajectory_publisher = rospy.Publisher(params.RVIZ_all_trajectory_topic, MarkerArray, queue_size=1)
        self._rviz_predi_trajectory_publisher = rospy.Publisher(params.RVIZ_predi_trajectory_topic, MarkerArray, queue_size=1)
        self._rviz_collision_circle_publisher = rospy.Publisher(params.RVIZ_collision_circle_topic, MarkerArray, queue_size=1)
        self._rviz_received_ref_path_publisher = rospy.Publisher(params.RVIZ_received_ref_path_topic, Path, queue_size=1)

    def loop(self):
        while not rospy.is_shutdown():
            publish_msg = self._decision_instance.update_trajectory()
            if publish_msg:
                self._decision_trajectory_publisher.publish(publish_msg)
                publish_msg2 = publish_msg.trajectory
                self._rviz_decision_trajectory_publisher.publish(publish_msg2)
                rospy.loginfo("continous model: PUBLISH: trajectory length = %d, desired_speed = %.1f", 
                    len(publish_msg.trajectory.poses), publish_msg.desired_speed)
            
            self.pub_rviz()
            
            # try:
            #     self.pub_rviz()
            # except:
            #     rospy.logerror("rviz_display failed")
                
            self._rate.sleep()
        
    def pub_rviz(self):
        all_trajectory = self._decision_instance._trajectory_planner.rivz_element.candidates_trajectory
        obs_paths = self._decision_instance._trajectory_planner.rivz_element.prediciton_trajectory
        collision_circle = self._decision_instance._trajectory_planner.rivz_element.collision_circle
        received_ref_path = self._decision_instance._trajectory_planner.ref_path_rviz
        
        if received_ref_path:
            self._rviz_received_ref_path_publisher.publish(received_ref_path)
        if all_trajectory:
            self._rviz_all_trajectory_publisher.publish(all_trajectory)
        if obs_paths:
            self._rviz_predi_trajectory_publisher.publish(obs_paths)
        if collision_circle:
            self._rviz_collision_circle_publisher.publish(collision_circle)
                
        
if __name__ == "__main__":

    rospy.init_node("decision_node", log_level=rospy.DEBUG)
    node = DecisionNode()
    node.loop()
