Header header

#novatel long header
LongHeader long_header

# Solution status
uint8 solution_status  
uint8 velocity_type
# measure of the latency of the velocity time tag in seconds
float32 latency  
# differential age in seconds
float32 age      
# horizontal speed in m/s
float64 horizontal_speed   
# direction of travel in degrees
float64 track_over_ground  
# vertical speed in m/s
float64 vertical_speed     
float32 reserved