#Ins_Pva
  Header header

#novatel long header
  LongHeader long_header

  uint32 gps_week

# seconds of week
  float64 gps_seconds     

# in degrees
  float64 latitude        

# in degrees
  float64 longitude       

# Ellipsoidal height - WGS84 (m)
  float64 height          

# velocity in a northerly direction (m/s)
  float64 north_velocity  

# velocity in an easterly direction (m/s)
  float64 east_velocity   

# velocity in an up direction
  float64 up_velocity     

# right handed rotation around y-axis (degrees)
  float64 roll            

# right handed rotation around x-axis (degrees)
  float64 pitch           

# left handed rotation around z-axis (degrees)
  float64 azimuth         

# status of the INS system
  uint32 status       